### ISSUE TITLE
Simulation error in DeNS

### ISSUE THREAD

**Issue by skylorh** [vamsiDT/DeNS#1]
hello, I'm trying to run the simulations in DeNS, which path is DeNS/simulations/dens_sc2/paper_cqf.ini
But at the begining of running the simulation, I find the mac module in hostPriority[0].eth[0] seems does not work. 
After the packet was sent to the mac module in hostPriority[0].eth[0], the conneted mac module in switchA.eth[0] received nothing.

I think the mismatch version of nesting may cause this error,but the latest version of nesting does not match DeNS, the url of the version I'm using is 
https://gitlab.com/ipvs/nesting/-/tree/53f8dbb65d2d88756d004cc8399c7c9937194e1a
Can you tell me the correct version of nesting for DeNS?

**Comment by vamsiDT** [comment]
Hello,
Thanks for your interest in DeNS.
Could you please try the following commit of Nesting?
$ git clone https://gitlab.com/ipvs/nesting.git

$ git checkout 2cbd94655f8cc63816b96e31732b8dcf99511378

Please let me know if there are any more errors.

**Comment by skylorh** [comment]
I modified some code in nesting(53f8dbb65d2d88756d004cc8399c7c9937194e1a) before, to fix some error in running the simulation. 
It seems the old way I'm trying to fix the error is wrong. 
But now it also works throughing a new way: 
modify the handleMessageWhenUp function in  EtherMACFullDuplexPreemptable.cc of nesting(53f8dbb65d2d88756d004cc8399c7c9937194e1a)
###
if (msg->isSelfMessage()) {
        handleSelfMessage(msg);
    } else if (msg->arrivedOn("upperLayerPreemptableIn")) {
        // preemptible from upper
        if (msg->isPacket()){
            handleUpperPacket(check_and_cast<Packet *>(msg));
        }
    } else if (msg->arrivedOn("upperLayerIn")) {
        // express from upper
        if (msg->isPacket()){
            handleUpperPacket(check_and_cast<Packet *>(msg));
        }
    }
### 
Thank you for your reply.
It seems that there is no new problem now. 
If there is any problem again, I will try the correct version next time.

**Comment by mesutren** [comment]
@

> I modified some code in nesting(53f8dbb65d2d88756d004cc8399c7c9937194e1a) before, to fix some error in running the simulation. It seems the old way I'm trying to fix the error is wrong. But now it also works throughing a new way: modify the handleMessageWhenUp function in EtherMACFullDuplexPreemptable.cc of nesting(53f8dbb65d2d88756d004cc8399c7c9937194e1a)
> 
> if (msg->isSelfMessage()) { handleSelfMessage(msg); } else if (msg->arrivedOn("upperLayerPreemptableIn")) { // preemptible from upper if (msg->isPacket()){ handleUpperPacket(check_and_cast<Packet *>(msg)); } } else if (msg->arrivedOn("upperLayerIn")) { // express from upper if (msg->isPacket()){ handleUpperPacket(check_and_cast<Packet *>(msg)); } }
> 
> Thank you for your reply. It seems that there is no new problem now. If there is any problem again, I will try the correct version next time.

Nice work! I met the same question with you and your modified codes solve the the problem perfectly!
